---
title: "Interactive chorddiag"
author: "Jamie Tam & Vahab Pourfaraj"
date: '2022-07-21'
output: html_document
Sources: https://github.com/NEFSC/READ-SSB-DePiper_Summer_Flounder_Conceptual_Models/blob/master/sfconsmod_final_2col.Rmd
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
require(igraph)
require(tidyverse)
require(visNetwork)
require(chorddiag)
require(circlize)
require(RColorBrewer)
```

## Interactive chordiag (chorddiag function) with chorddiag package

```{r}
kumu.data<-read_csv("IMSES-subset-test_AUG2.csv")
kumu.data<-kumu.data[,c(1,2,8)] #save columns "From", "To" and "Strength"
kumu.graph<- graph_from_data_frame(kumu.data,directed = TRUE, vertices = NULL ) #this line added to convert data to a graph object for next line
kumu.adj.mat<-as_adjacency_matrix(kumu.graph, attr= "Strength" , sparse=FALSE)


nodes<- read.csv("pilars.csv")
climate_dim <- filter(nodes, group=="Climate")
climate_nodes<- climate_dim$label

ecol_dim <- filter(nodes, group=="Ecological")
ecol_nodes<- ecol_dim$label

gov_dim <- filter(nodes, group=="Governance")
gov_nodes<- gov_dim$label

rights_dim <- filter(nodes, group=="Indeginous rights & reconciliation")
rights_nodes<- rights_dim$label

econ_dim <- filter(nodes, group=="Economic")
econ_nodes<- econ_dim$label

social_dim <- filter(nodes, group=="Socio-cultural")
social_nodes<- social_dim$label

nodescolorselect <- brewer.pal(6, "Dark2")
mapcolordf <- data.frame(row.names(kumu.adj.mat))
colnames(mapcolordf) <- "focus"

mapcolordf$color <- nodescolorselect[1]
mapcolordf$color[mapcolordf$focus%in%ecol_nodes] <- nodescolorselect[2] 
mapcolordf$color[mapcolordf$focus%in%gov_nodes] <- nodescolorselect[3] 
mapcolordf$color[mapcolordf$focus%in%rights_nodes] <- nodescolorselect[4] 
mapcolordf$color[mapcolordf$focus%in%econ_nodes] <- nodescolorselect[5] 
mapcolordf$color[mapcolordf$focus%in%social_nodes] <- nodescolorselect[6] 

IMSES_Groups <- mapcolordf


IMSES_Groups$Group <- "Climate"
IMSES_Groups$Rank <- 1
IMSES_Groups$Group[IMSES_Groups$focus%in%ecol_nodes] <- "Ecological"
IMSES_Groups$Rank[IMSES_Groups$focus%in%ecol_nodes] <- 2
IMSES_Groups$Group[IMSES_Groups$focus%in%gov_nodes] <- "Governance"
IMSES_Groups$Rank[IMSES_Groups$focus%in%gov_nodes] <- 3
IMSES_Groups$Group[IMSES_Groups$focus%in%rights_nodes] <- "Indeginous rights & reconciliation"
IMSES_Groups$Rank[IMSES_Groups$focus%in%rights_nodes] <- 4
IMSES_Groups$Group[IMSES_Groups$focus%in%econ_nodes] <- "Economic"
IMSES_Groups$Rank[IMSES_Groups$focus%in%econ_nodes] <- 5
IMSES_Groups$Group[IMSES_Groups$focus%in%social_nodes] <- "Socio-cultural"
IMSES_Groups$Rank[IMSES_Groups$focus%in%social_nodes] <- 6

map_edges <- cbind(kumu.adj.mat,mapcolordf)
mapcolordf <- mapcolordf[order(mapcolordf$color,mapcolordf$focus),]
mapcolordf <- matrix(mapcolordf$color,dimnames=list(mapcolordf$focus,"Color"))
map_edges <-  map_edges[order( map_edges$color,map_edges$focus),]

map_edges$color <- NULL
map_edges$focus <- NULL
rn <- row.names(map_edges)
map_edges2 <- map_edges[rn]
map_edges <- data.matrix(map_edges)
map_edges2 <- data.matrix(map_edges2)
#map_edges2 <- t(map_edges2)  not sure why Ben transposed the matrix?!
map_edges2 <- abs(map_edges2)
#########Submodels functions
Submodel_edges <- function (y) {
  New_edges <- map_edges2[,colnames(map_edges2)%in%y]
  New_edges <- New_edges[rownames(New_edges)%in%y,]
  return(New_edges)
}
Submodel_color <- function (y) {
  New_colors <-  as.vector(mapcolordf[rownames(mapcolordf)%in%y,])
  return(New_colors)
}
New_Figure <- function (x) {
  New_edges <- Submodel_edges(x)
  New_colors <- Submodel_color(x)
  New_groups <- IMSES_Groups[which(IMSES_Groups$focus%in%x),]
  New_groups <- unique(New_groups[,2:4])
  New_groups <- New_groups[order(New_groups$Rank),]
  New_groups <- New_groups[,1:2]
  Figure_name <- deparse(substitute(x))
  Figure_title <- gsub("_"," ",Figure_name)
  chorddiag(New_edges, 
            type = "directional",
            width = NULL,
            height = NULL,
            margin = 110,
            groupColors = New_colors,
            groupedgeColor = New_colors,
            chordedgeColor = New_colors,
            groupPadding = 3, groupThickness = 0.05,
            showTicks = F, groupnameFontsize = 12, groupnamePadding = 8
  )
}

```
```{r}
#full model and subsets
#subset_model<- nodes$label[nodes$group=="Ecological"|nodes$group=="Climate"]
#New_Figure(subset_model)

New_Figure(nodes$label)
```

